### ISSUE TITLE
flutter build macos failed

### ISSUE THREAD

**Issue by joeycold** [Moosphan/flutter_mobile_controller#17]
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64,
    locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK
    version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] VS Code (version 1.65.2)

> flutter build macos
Running "flutter pub get" in flutter_mobile_controller...                 780ms
>
>💪 Building with sound null safety 💪
>
>Running pod install...                                                  1,171ms
Building macOS application...                                          2022-03-31 17:04:04.188 xcodebuild[82609:5160111] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Building macOS application...                                          2022-03-31 17:04:04.189 xcodebuild[82609:5160111] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Building macOS application...                                          --- xcodebuild: WARNING: Using the first of multiple matching destinations:
Building macOS application...                                          { platform:macOS, arch:x86_64, id:4F8DD380-23F3-5092-A7FD-00E93833831C }
Building macOS application...                                          { platform:macOS, name:Any Mac }
Building macOS application...                                          Building App.framework for x86_64...
Building macOS application...                                          Codepoint 65593 not found in font, aborting.
Building macOS application...                                          
Building macOS application...                                          
Building macOS application...                                          Command PhaseScriptExecution failed with a nonzero exit code
Building macOS application...                                          note: Using new build system
Building macOS application...                                          note: Planning
Building macOS application...                                          note: Build preparation complete
Building macOS application...                                          note: Building targets in dependency order
Building macOS application...                                          ** BUILD FAILED **
Building macOS application...                                          
Building macOS application...                                           
Build process failed

how to fix this? shoud i need `-v` to give more detailed log?

**Comment by Moosphan** [comment]
@joeycold You can try to switch your channel to `master` or upgrade flutter version to 2.11.0
